require("config.pachulski.opts").setup()
require("config.pachulski.autocmds").setup()
require("config.pachulski.diagnostics").setup()
require("config.pachulski.keymaps").setup()
require("config.pachulski.vim_test").setup()
