return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			highlight = { enable = true },
			indent = { enable = true },
			incremental_selection = { enable = true },
			autotag = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"elixir",
				"elm",
				"git_config",
				"git_rebase",
				"gitcommit",
				"gitignore",
				"go",
				"html",
				"java",
				"javascript",
				"json",
				"lua",
				"markdown",
				"markdown_inline",
				"objc",
				"python",
				"ruby",
				"scss",
				"swift",
				"tmux",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
			},
		})
	end,
}
