-- do not edit this file directly
--
-- this file is auto-generated by update-theme.sh
--
-- edit ~/.config/theme to change your nvim theme

return {
  dark = {
    name = "catppuccin-frappe",
    style = "dark",
  },
  light = {
    name = "gruvbox",
    style = "light",
  },
}
