git:
  commitEditing: external
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  paging:
    colorArg: always
    pager: "delta --paging=never"
